# Exceptions
Dealing with execptions in python

<details>
<summary><b>0-safe_print_list</b></summary>
python function prints x elements of a list.
</details>

---

<details>
<summary><b>1-safe_print_integers</b></summary>
python function that prints an integer with
```python
"{:d}".format()
```
</details>

---

<details>
<summary><b>2-safe_print_list_interges</b></summary>
python function that prints the first x elements of a list and only integers.
</details>

---

<details>
<summary><b>3-safe_print_division</b></summary>
function that divides 2 integers and prints the result.
</details>

---

<details>
<summary><b>4-list_division</b></summary>
python function that divides element by element 2 lists.</details>

---

<details>
<summary><b>5-raise_exception</b></summary>
python function that raises a type exception.
</details>

---

<details>
<summary><b>6-raise_exception_msg</b></summary>
python function that raises a name exception with a message.
</details>
